version: "3.8"

services:
  db:
    image: postgres:14
    volumes:
      - ./server/db:/opt/backup
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
